### ISSUE TITLE
Doubts about a PowerShell command.

### ISSUE THREAD

**Issue by ghost** [1mm0rt41PC/SecureDomain#1]
The LAPS.md documentation has a command called `New-GPOChoco,` while creating the GPOs. Can you explain what it does, and provide any documentation? I cannot find anything on the internet about that command.

**Comment by 1mm0rt41PC** [comment]
Hello !
It was a tipo, the correct function is `New-GPOSchTask` from https://github.com/1mm0rt41PC/SecureDomain/blob/master/Function_New-GPOSchTask.ps1
